import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Очистка базы данных...");
  await prisma.experience.deleteMany();
  await prisma.candidateNote.deleteMany();
  await prisma.screeningResult.deleteMany();
  await prisma.detailedScore.deleteMany();
  await prisma.matchResult.deleteMany();
  await prisma.candidate.deleteMany();
  await prisma.vacancy.deleteMany();

  console.log("Создание кандидатов...");

  const candidates = [
    {
      name: "Анна Петрова",
      role: "PRODUCT_DESIGNER" as const,
      grade: "SENIOR" as const,
      yearsOfExperience: 6,
      specializations: ["product design", "design systems"],
      domains: ["fintech", "SaaS"],
      segment: "B2B" as const,
      platforms: ["web", "mobile"],
      skills: ["product thinking", "prototyping", "user research", "design systems", "data-driven design"],
      tools: ["Figma", "Miro", "Notion"],
      location: "Москва",
      email: "anna.petrova@example.com",
      hasBigtechExperience: true,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "Сильный продуктовый дизайнер с опытом в финтехе. Умеет строить дизайн-системы, работает с метриками. Хорошее продуктовое мышление.",
      aiStrengths: ["Опыт построения дизайн-систем с нуля", "Понимание бизнес-метрик", "Умение работать с продуктовой командой"],
      aiConcerns: ["Нет международного опыта"],
      aiConfidenceScore: 90,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Тинькофф", role: "Senior Product Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Построила дизайн-систему для внутренних продуктов", "Увеличила конверсию на 25%"], isBigtech: true, isStudio: false },
        { company: "Яндекс", role: "Product Designer", startDate: "2018", endDate: "2021", duration: "3 года", keyAchievements: ["Работа над Яндекс.Маркет"], isBigtech: true, isStudio: false },
      ],
    },
    {
      name: "Иван Сидоров",
      role: "UX_DESIGNER" as const,
      grade: "MIDDLE_PLUS" as const,
      yearsOfExperience: 4,
      specializations: ["UX design", "UX research"],
      domains: ["e-commerce", "marketplace"],
      segment: "B2C" as const,
      platforms: ["web", "mobile"],
      skills: ["user research", "usability testing", "wireframing", "information architecture"],
      tools: ["Figma", "Maze", "Hotjar"],
      location: "Санкт-Петербург",
      email: "ivan.sidorov@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: true,
      hasInternationalExperience: false,
      aiSummary: "UX-дизайнер с фокусом на исследования. Сильный в юзабилити-тестировании и информационной архитектуре.",
      aiStrengths: ["Глубокое понимание UX-исследований", "Опыт работы со сложными интерфейсами"],
      aiConcerns: ["Слабый визуальный дизайн", "Нет опыта в B2B"],
      aiConfidenceScore: 85,
      status: "ACTIVE" as const,
      experiences: [
        { company: "AIC", role: "UX Designer", startDate: "2022", endDate: "2024", duration: "2 года", keyAchievements: ["Провёл 30+ юзабилити-тестов", "Редизайн каталога товаров"], isBigtech: false, isStudio: true },
        { company: "Ozon", role: "Junior UX Designer", startDate: "2020", endDate: "2022", duration: "2 года", keyAchievements: ["Оптимизация checkout flow"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Мария Козлова",
      role: "UI_DESIGNER" as const,
      grade: "SENIOR_PLUS" as const,
      yearsOfExperience: 8,
      specializations: ["UI design", "visual design", "motion design"],
      domains: ["banking", "fintech"],
      segment: "B2C" as const,
      platforms: ["mobile"],
      skills: ["visual design", "motion design", "prototyping", "brand identity"],
      tools: ["Figma", "After Effects", "Principle"],
      location: "Москва",
      email: "maria.kozlova@example.com",
      hasBigtechExperience: true,
      hasStudioExperience: false,
      hasInternationalExperience: true,
      aiSummary: "Визуально сильный UI-дизайнер с опытом в мобильных приложениях для банков. Работала в международных командах.",
      aiStrengths: ["Отличный визуальный вкус", "Опыт motion-дизайна", "Международный опыт"],
      aiConcerns: ["Меньше опыта в продуктовом мышлении"],
      aiConfidenceScore: 92,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Revolut", role: "Senior UI Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Редизайн основного мобильного приложения", "Создание motion-библиотеки"], isBigtech: true, isStudio: false },
        { company: "Сбербанк", role: "UI Designer", startDate: "2016", endDate: "2021", duration: "5 лет", keyAchievements: ["Дизайн СберБанк Онлайн"], isBigtech: true, isStudio: false },
      ],
    },
    {
      name: "Алексей Волков",
      role: "PRODUCT_DESIGNER" as const,
      grade: "MIDDLE" as const,
      yearsOfExperience: 3,
      specializations: ["product design"],
      domains: ["edtech", "SaaS"],
      segment: "B2B" as const,
      platforms: ["web"],
      skills: ["product thinking", "wireframing", "prototyping"],
      tools: ["Figma", "Notion"],
      location: "Казань",
      email: "alexey.volkov@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "Растущий продуктовый дизайнер. Хорошо справляется с типовыми задачами, но пока без глубокого опыта в сложных доменах.",
      aiStrengths: ["Быстрый в работе", "Хорошее понимание продукта"],
      aiConcerns: ["Мало опыта", "Нет сложных доменов в портфолио"],
      aiConfidenceScore: 80,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Skyeng", role: "Product Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Дизайн нового раздела домашних заданий"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Елена Новикова",
      role: "DESIGN_LEAD" as const,
      grade: "LEAD" as const,
      yearsOfExperience: 10,
      specializations: ["product design", "design management", "design strategy"],
      domains: ["fintech", "enterprise", "SaaS"],
      segment: "B2B" as const,
      platforms: ["web", "mobile", "desktop"],
      skills: ["team management", "design strategy", "stakeholder management", "mentoring", "design systems"],
      tools: ["Figma", "Miro", "Confluence", "Jira"],
      location: "Москва",
      email: "elena.novikova@example.com",
      hasBigtechExperience: true,
      hasStudioExperience: true,
      hasInternationalExperience: true,
      aiSummary: "Опытный дизайн-лид с сильными управленческими навыками. Строила дизайн-команды с нуля, опыт в enterprise и fintech.",
      aiStrengths: ["Опыт управления командами до 15 человек", "Стратегическое мышление", "Bigtech + studio опыт"],
      aiConcerns: [],
      aiConfidenceScore: 95,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Авито", role: "Design Lead", startDate: "2020", endDate: "2024", duration: "4 года", keyAchievements: ["Выстроила дизайн-процессы для 3 продуктовых команд", "Наняла и развила команду из 12 дизайнеров"], isBigtech: true, isStudio: false },
        { company: "Mail.ru", role: "Senior Designer", startDate: "2017", endDate: "2020", duration: "3 года", keyAchievements: ["Редизайн Облака Mail.ru"], isBigtech: true, isStudio: false },
        { company: "Charmer", role: "Designer", startDate: "2014", endDate: "2017", duration: "3 года", keyAchievements: ["Дизайн для 20+ клиентов"], isBigtech: false, isStudio: true },
      ],
    },
    {
      name: "Дмитрий Морозов",
      role: "UX_RESEARCHER" as const,
      grade: "SENIOR" as const,
      yearsOfExperience: 5,
      specializations: ["UX research", "user interviews", "quantitative research"],
      domains: ["fintech", "healthcare"],
      segment: "BOTH" as const,
      platforms: ["web", "mobile"],
      skills: ["user interviews", "surveys", "A/B testing", "analytics", "journey mapping"],
      tools: ["Dovetail", "Maze", "Google Analytics", "Miro"],
      location: "Москва",
      email: "dmitry.morozov@example.com",
      hasBigtechExperience: true,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "Сильный UX-исследователь с аналитическим складом ума. Опыт в fintech и healthcare, умеет работать с данными.",
      aiStrengths: ["Сочетание качественных и количественных методов", "Опыт в регулируемых доменах"],
      aiConcerns: ["Не дизайнер — чистый исследователь"],
      aiConfidenceScore: 88,
      status: "ACTIVE" as const,
      experiences: [
        { company: "СберЗдоровье", role: "Senior UX Researcher", startDate: "2022", endDate: "2024", duration: "2 года", keyAchievements: ["Построил процесс исследований с нуля", "40+ глубинных интервью"], isBigtech: true, isStudio: false },
        { company: "Альфа-Банк", role: "UX Researcher", startDate: "2019", endDate: "2022", duration: "3 года", keyAchievements: ["A/B тестирование новых фичей"], isBigtech: true, isStudio: false },
      ],
    },
    {
      name: "Ольга Белова",
      role: "PRODUCT_DESIGNER" as const,
      grade: "SENIOR" as const,
      yearsOfExperience: 7,
      specializations: ["product design", "enterprise UX"],
      domains: ["enterprise", "B2B SaaS", "CRM"],
      segment: "B2B" as const,
      platforms: ["web", "desktop"],
      skills: ["complex interfaces", "design systems", "product thinking", "enterprise UX"],
      tools: ["Figma", "Storybook", "Jira"],
      location: "Новосибирск",
      email: "olga.belova@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: true,
      aiSummary: "Enterprise-дизайнер с глубоким пониманием сложных B2B-интерфейсов. Опыт работы с CRM и аналитическими дашбордами.",
      aiStrengths: ["Глубокий опыт в enterprise UX", "Умение работать со сложными данными", "Международный опыт"],
      aiConcerns: ["Нет мобильного опыта"],
      aiConfidenceScore: 87,
      status: "ACTIVE" as const,
      experiences: [
        { company: "JetBrains", role: "Senior Product Designer", startDate: "2020", endDate: "2024", duration: "4 года", keyAchievements: ["Дизайн нового инструмента для DevOps", "Построила дизайн-систему"], isBigtech: false, isStudio: false },
        { company: "amoCRM", role: "Product Designer", startDate: "2017", endDate: "2020", duration: "3 года", keyAchievements: ["Редизайн CRM-интерфейса"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Артём Кузнецов",
      role: "MOTION_DESIGNER" as const,
      grade: "MIDDLE_PLUS" as const,
      yearsOfExperience: 4,
      specializations: ["motion design", "interaction design"],
      domains: ["entertainment", "social media"],
      segment: "B2C" as const,
      platforms: ["mobile"],
      skills: ["animation", "interaction design", "prototyping", "3D"],
      tools: ["After Effects", "Principle", "Figma", "Blender"],
      location: "Москва",
      email: "artem.kuznetsov@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: true,
      hasInternationalExperience: false,
      aiSummary: "Motion-дизайнер с хорошим чувством анимации. Работает на стыке interaction и motion design.",
      aiStrengths: ["Сильные анимации и микровзаимодействия", "Опыт 3D"],
      aiConcerns: ["Узкая специализация", "Мало продуктового опыта"],
      aiConfidenceScore: 82,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Студия Лебедева", role: "Motion Designer", startDate: "2022", endDate: "2024", duration: "2 года", keyAchievements: ["Анимации для 10+ мобильных приложений"], isBigtech: false, isStudio: true },
        { company: "Freelance", role: "Motion Designer", startDate: "2020", endDate: "2022", duration: "2 года", keyAchievements: [], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Наталья Смирнова",
      role: "PRODUCT_DESIGNER" as const,
      grade: "JUNIOR" as const,
      yearsOfExperience: 1,
      specializations: ["product design"],
      domains: ["e-commerce"],
      segment: "B2C" as const,
      platforms: ["web"],
      skills: ["wireframing", "prototyping", "Figma"],
      tools: ["Figma"],
      location: "Москва",
      email: "natalya.smirnova@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "Начинающий дизайнер с потенциалом. Хорошее портфолио для джуна, но мало реального опыта.",
      aiStrengths: ["Аккуратность", "Быстро учится"],
      aiConcerns: ["Мало коммерческого опыта", "Нет сложных проектов"],
      aiConfidenceScore: 75,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Стажировка в Lamoda", role: "Junior Designer", startDate: "2023", endDate: "2024", duration: "1 год", keyAchievements: ["Дизайн карточек товаров"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Сергей Попов",
      role: "ART_DIRECTOR" as const,
      grade: "SENIOR_PLUS" as const,
      yearsOfExperience: 9,
      specializations: ["art direction", "brand design", "visual design"],
      domains: ["media", "entertainment", "luxury"],
      segment: "B2C" as const,
      platforms: ["web", "mobile"],
      skills: ["art direction", "brand identity", "visual design", "typography", "team management"],
      tools: ["Figma", "Photoshop", "Illustrator", "InDesign"],
      location: "Москва",
      email: "sergey.popov@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: true,
      hasInternationalExperience: true,
      aiSummary: "Арт-директор с сильным визуальным вкусом. Опыт в брендинге и editorial дизайне, работал с luxury-брендами.",
      aiStrengths: ["Исключительный визуальный вкус", "Широкий опыт в брендинге", "Международные клиенты"],
      aiConcerns: ["Мало продуктового опыта", "Скорее графический дизайнер, чем продуктовый"],
      aiConfidenceScore: 85,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Bang Bang Education", role: "Art Director", startDate: "2020", endDate: "2024", duration: "4 года", keyAchievements: ["Ребрендинг платформы", "Управление командой из 5 дизайнеров"], isBigtech: false, isStudio: true },
        { company: "Depot WPF", role: "Senior Designer", startDate: "2015", endDate: "2020", duration: "5 лет", keyAchievements: ["Работа с 30+ брендами"], isBigtech: false, isStudio: true },
      ],
    },
    {
      name: "Татьяна Лебедева",
      role: "PRODUCT_DESIGNER" as const,
      grade: "SENIOR" as const,
      yearsOfExperience: 6,
      specializations: ["product design", "mobile design"],
      domains: ["travel", "marketplace", "e-commerce"],
      segment: "B2C" as const,
      platforms: ["mobile", "web"],
      skills: ["mobile design", "product thinking", "prototyping", "user research"],
      tools: ["Figma", "Principle", "Miro"],
      location: "Москва",
      email: "tatyana.lebedeva@example.com",
      hasBigtechExperience: true,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "Продуктовый дизайнер с фокусом на мобильные приложения. Сильный опыт в marketplace и travel.",
      aiStrengths: ["Глубокий мобильный опыт", "Понимание e-commerce метрик", "Bigtech бэкграунд"],
      aiConcerns: ["Нет B2B опыта"],
      aiConfidenceScore: 89,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Aviasales", role: "Senior Product Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Редизайн мобильного приложения", "Рост конверсии на 18%"], isBigtech: false, isStudio: false },
        { company: "Wildberries", role: "Product Designer", startDate: "2018", endDate: "2021", duration: "3 года", keyAchievements: ["Дизайн корзины и чекаута"], isBigtech: true, isStudio: false },
      ],
    },
    {
      name: "Константин Орлов",
      role: "UX_DESIGNER" as const,
      grade: "SENIOR" as const,
      yearsOfExperience: 7,
      specializations: ["UX design", "service design", "accessibility"],
      domains: ["government", "healthcare", "enterprise"],
      segment: "B2B" as const,
      platforms: ["web"],
      skills: ["service design", "accessibility", "information architecture", "user research", "complex workflows"],
      tools: ["Figma", "Axure", "Miro"],
      location: "Санкт-Петербург",
      email: "konstantin.orlov@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: true,
      hasInternationalExperience: false,
      aiSummary: "UX-дизайнер со специализацией на accessibility и сложных корпоративных системах. Редкий опыт в госсекторе.",
      aiStrengths: ["Экспертиза в accessibility", "Опыт со сложными процессами", "Service design"],
      aiConcerns: ["Консервативный подход к визуалу", "Может быть overqualified для стартапов"],
      aiConfidenceScore: 86,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Ростелеком", role: "Senior UX Designer", startDate: "2020", endDate: "2024", duration: "4 года", keyAchievements: ["Проектирование ГосУслуг 2.0", "Внедрение стандартов accessibility"], isBigtech: false, isStudio: false },
        { company: "UsabilityLab", role: "UX Designer", startDate: "2017", endDate: "2020", duration: "3 года", keyAchievements: ["50+ UX-аудитов"], isBigtech: false, isStudio: true },
      ],
    },
    {
      name: "Виктория Фёдорова",
      role: "COMMUNICATION_DESIGNER" as const,
      grade: "MIDDLE" as const,
      yearsOfExperience: 3,
      specializations: ["communication design", "brand identity"],
      domains: ["FMCG", "retail"],
      segment: "B2C" as const,
      platforms: ["web"],
      skills: ["brand identity", "marketing design", "illustration", "typography"],
      tools: ["Figma", "Illustrator", "Photoshop"],
      location: "Екатеринбург",
      email: "victoria.fedorova@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: true,
      hasInternationalExperience: false,
      aiSummary: "Коммуникационный дизайнер с фокусом на бренд-айдентику. Сильна в иллюстрации и типографике.",
      aiStrengths: ["Иллюстрация", "Типографика", "Брендинг"],
      aiConcerns: ["Нет продуктового опыта", "Только коммуникационный дизайн"],
      aiConfidenceScore: 78,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Nimax", role: "Communication Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Брендинг для 15+ компаний"], isBigtech: false, isStudio: true },
      ],
    },
    {
      name: "Павел Григорьев",
      role: "PRODUCT_DESIGNER" as const,
      grade: "MIDDLE_PLUS" as const,
      yearsOfExperience: 4,
      specializations: ["product design", "data visualization"],
      domains: ["analytics", "BI", "SaaS"],
      segment: "B2B" as const,
      platforms: ["web"],
      skills: ["data visualization", "dashboards", "complex interfaces", "design systems"],
      tools: ["Figma", "D3.js", "Storybook"],
      location: "Москва",
      email: "pavel.grigoriev@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: true,
      aiSummary: "Продуктовый дизайнер с редкой специализацией в data visualization. Работает с аналитическими дашбордами.",
      aiStrengths: ["Data visualization — редкий навык", "Понимание сложных данных", "Международный опыт"],
      aiConcerns: ["Узкая специализация"],
      aiConfidenceScore: 84,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Qlik", role: "Product Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Дизайн нового аналитического модуля"], isBigtech: false, isStudio: false },
        { company: "CleverDATA", role: "Designer", startDate: "2020", endDate: "2021", duration: "1 год", keyAchievements: [], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Екатерина Васильева",
      role: "PRODUCT_DESIGNER" as const,
      grade: "SENIOR" as const,
      yearsOfExperience: 6,
      specializations: ["product design", "growth design"],
      domains: ["fintech", "crypto", "trading"],
      segment: "B2C" as const,
      platforms: ["mobile", "web"],
      skills: ["growth design", "A/B testing", "conversion optimization", "product thinking"],
      tools: ["Figma", "Amplitude", "Mixpanel"],
      location: "Лимассол",
      email: "ekaterina.vasilyeva@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: true,
      aiSummary: "Growth-дизайнер с сильным пониманием метрик. Опыт в криптовалютных и trading-платформах.",
      aiStrengths: ["Growth-мышление", "Работа с метриками", "Опыт в trading UI"],
      aiConcerns: ["Узкий домен (крипто)", "Может не подойти для enterprise"],
      aiConfidenceScore: 86,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Bybit", role: "Senior Product Designer", startDate: "2022", endDate: "2024", duration: "2 года", keyAchievements: ["Рост конверсии регистрации на 35%", "Дизайн trading dashboard"], isBigtech: false, isStudio: false },
        { company: "Revolut", role: "Product Designer", startDate: "2019", endDate: "2022", duration: "3 года", keyAchievements: ["Дизайн crypto-раздела"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Андрей Михайлов",
      role: "BRAND_DESIGNER" as const,
      grade: "MIDDLE" as const,
      yearsOfExperience: 3,
      specializations: ["brand design", "visual identity"],
      domains: ["startups", "tech"],
      segment: "B2C" as const,
      platforms: ["web"],
      skills: ["brand identity", "logo design", "visual design", "presentation design"],
      tools: ["Figma", "Illustrator", "Photoshop"],
      location: "Москва",
      email: "andrey.mikhailov@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: true,
      hasInternationalExperience: false,
      aiSummary: "Бренд-дизайнер с хорошим портфолио логотипов и айдентик. Работал со стартапами.",
      aiStrengths: ["Чистый визуальный стиль", "Быстрый в работе"],
      aiConcerns: ["Нет продуктового опыта", "Только брендинг"],
      aiConfidenceScore: 76,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Студия Артемия Лебедева", role: "Brand Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["20+ айдентик для стартапов"], isBigtech: false, isStudio: true },
      ],
    },
    {
      name: "Анастасия Егорова",
      role: "PRODUCT_DESIGNER" as const,
      grade: "MIDDLE" as const,
      yearsOfExperience: 3,
      specializations: ["product design"],
      domains: ["HR tech", "SaaS"],
      segment: "B2B" as const,
      platforms: ["web"],
      skills: ["product thinking", "prototyping", "user research", "wireframing"],
      tools: ["Figma", "Notion", "Miro"],
      location: "Москва",
      telegramContact: "@anastasia_egorova",
      email: "anastasia.egorova@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "Продуктовый дизайнер в HR tech. Понимает специфику B2B SaaS, но пока без опыта в крупных продуктах.",
      aiStrengths: ["Понимание B2B SaaS", "Хороший UX-процесс"],
      aiConcerns: ["Небольшой опыт", "Нет bigtech"],
      aiConfidenceScore: 79,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Хантфлоу", role: "Product Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Дизайн ATS-системы", "Улучшение воронки найма"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Максим Соколов",
      role: "PRODUCT_DESIGNER" as const,
      grade: "SENIOR_PLUS" as const,
      yearsOfExperience: 8,
      specializations: ["product design", "design systems", "mobile design"],
      domains: ["super-app", "fintech", "marketplace"],
      segment: "BOTH" as const,
      platforms: ["mobile", "web"],
      skills: ["design systems", "mobile design", "product strategy", "team collaboration", "metrics"],
      tools: ["Figma", "Storybook", "Miro", "Jira"],
      location: "Москва",
      email: "maxim.sokolov@example.com",
      hasBigtechExperience: true,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "Сильный senior+ дизайнер с опытом в super-app и крупных мобильных продуктах. Построил несколько дизайн-систем.",
      aiStrengths: ["Опыт super-app архитектуры", "Дизайн-системы", "Bigtech background", "Работа с метриками"],
      aiConcerns: [],
      aiConfidenceScore: 93,
      status: "ACTIVE" as const,
      experiences: [
        { company: "ВКонтакте", role: "Senior Product Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Дизайн-система VK UI", "Дизайн VK Mini Apps"], isBigtech: true, isStudio: false },
        { company: "Яндекс.Go", role: "Product Designer", startDate: "2018", endDate: "2021", duration: "3 года", keyAchievements: ["Дизайн основных сценариев super-app"], isBigtech: true, isStudio: false },
        { company: "ДоДо Пицца", role: "Designer", startDate: "2016", endDate: "2018", duration: "2 года", keyAchievements: ["Мобильное приложение"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Юлия Андреева",
      role: "UX_DESIGNER" as const,
      grade: "MIDDLE" as const,
      yearsOfExperience: 2,
      specializations: ["UX design"],
      domains: ["logistics", "delivery"],
      segment: "B2B" as const,
      platforms: ["web", "mobile"],
      skills: ["wireframing", "user flows", "usability testing"],
      tools: ["Figma", "Miro"],
      location: "Воронеж",
      email: "yulia.andreeva@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: false,
      aiSummary: "UX-дизайнер с опытом в логистике. Растущий специалист, хорошо работает с user flows.",
      aiStrengths: ["Хорошее понимание процессов", "Детальные user flows"],
      aiConcerns: ["Мало опыта", "Слабый визуал"],
      aiConfidenceScore: 74,
      status: "ACTIVE" as const,
      experiences: [
        { company: "СДЭК", role: "UX Designer", startDate: "2022", endDate: "2024", duration: "2 года", keyAchievements: ["Редизайн личного кабинета партнёра"], isBigtech: false, isStudio: false },
      ],
    },
    {
      name: "Роман Тарасов",
      role: "PRODUCT_DESIGNER" as const,
      grade: "SENIOR" as const,
      yearsOfExperience: 5,
      specializations: ["product design", "no-code tools"],
      domains: ["developer tools", "no-code", "SaaS"],
      segment: "B2B" as const,
      platforms: ["web"],
      skills: ["product thinking", "design systems", "developer experience", "information architecture"],
      tools: ["Figma", "Framer", "Webflow", "Storybook"],
      timezone: "UTC+3",
      email: "roman.tarasov@example.com",
      hasBigtechExperience: false,
      hasStudioExperience: false,
      hasInternationalExperience: true,
      aiSummary: "Продуктовый дизайнер со специализацией в developer tools и no-code. Работает удалённо, международный опыт.",
      aiStrengths: ["Редкая специализация — developer tools", "Понимание DX", "Работа с no-code платформами"],
      aiConcerns: ["Нет bigtech", "Узкая ниша"],
      aiConfidenceScore: 83,
      status: "ACTIVE" as const,
      experiences: [
        { company: "Tilda", role: "Senior Product Designer", startDate: "2021", endDate: "2024", duration: "3 года", keyAchievements: ["Дизайн нового блочного редактора", "Рост вовлечённости на 40%"], isBigtech: false, isStudio: false },
        { company: "Readymag", role: "Product Designer", startDate: "2019", endDate: "2021", duration: "2 года", keyAchievements: ["Дизайн animation engine"], isBigtech: false, isStudio: false },
      ],
    },
  ];

  for (const c of candidates) {
    const { experiences, ...data } = c;
    await prisma.candidate.create({
      data: {
        ...data,
        experiences: {
          create: experiences,
        },
      },
    });
  }

  console.log(`Создано ${candidates.length} кандидатов`);

  console.log("Создание вакансий...");

  await prisma.vacancy.create({
    data: {
      title: "Senior Product Designer — Fintech B2B",
      status: "OPEN",
      clientName: "КрупныйБанк",
      clientLead: "Алексей Иванов",
      productDescription: "Внутренняя платформа для корпоративных клиентов банка. Сложные финансовые интерфейсы, дашборды, аналитика.",
      reasonForHiring: "Расширение команды, новый продукт для юрлиц",
      role: "PRODUCT_DESIGNER",
      grade: "SENIOR",
      designersNeeded: 1,
      employmentType: "FULL_TIME",
      workFormat: "HYBRID",
      location: "Москва",
      salaryRange: "250 000 - 350 000 ₽",
      keyTasks: [
        "Проектирование сложных финансовых интерфейсов",
        "Работа с дизайн-системой",
        "Взаимодействие с продуктовой командой",
        "Проведение UX-исследований",
      ],
      requiredSkills: ["product thinking", "design systems", "complex interfaces", "prototyping"],
      niceToHaveSkills: ["data visualization", "accessibility", "user research"],
      preferredDomains: ["fintech", "enterprise", "B2B SaaS"],
      requiredTools: ["Figma"],
      specialCompetencies: ["enterprise UX", "financial dashboards"],
      redFlags: ["только мобильный опыт", "только брендинг"],
      teamComposition: "PM, 2 разработчика, аналитик, тестировщик",
      decisionMaker: "Head of Design",
      hiringStages: 3,
      scoringCriteria: [
        { criterion: "Опыт в fintech / enterprise", weight: 25, type: "required" },
        { criterion: "Продуктовое мышление", weight: 20, type: "required" },
        { criterion: "Дизайн-системы", weight: 15, type: "required" },
        { criterion: "Сложные интерфейсы и дашборды", weight: 15, type: "required" },
        { criterion: "UX-исследования", weight: 10, type: "nice_to_have" },
        { criterion: "Работа с метриками", weight: 10, type: "nice_to_have" },
        { criterion: "Международный опыт", weight: 5, type: "nice_to_have" },
      ],
    },
  });

  await prisma.vacancy.create({
    data: {
      title: "Middle+ Product Designer — EdTech",
      status: "OPEN",
      clientName: "EdPlatform",
      clientLead: "Мария Светлова",
      productDescription: "Образовательная платформа для онлайн-курсов. Мобильное приложение + веб-версия. Аудитория — студенты 18-35 лет.",
      reasonForHiring: "Замена ушедшего дизайнера",
      role: "PRODUCT_DESIGNER",
      grade: "MIDDLE_PLUS",
      designersNeeded: 1,
      employmentType: "FULL_TIME",
      workFormat: "REMOTE",
      salaryRange: "180 000 - 250 000 ₽",
      keyTasks: [
        "Дизайн мобильного приложения",
        "Улучшение пользовательского опыта обучения",
        "Работа с геймификацией",
        "A/B тесты",
      ],
      requiredSkills: ["mobile design", "product thinking", "prototyping"],
      niceToHaveSkills: ["gamification", "A/B testing", "motion design"],
      preferredDomains: ["edtech", "e-commerce", "B2C"],
      requiredTools: ["Figma"],
      specialCompetencies: ["mobile-first design"],
      redFlags: ["только B2B", "только enterprise"],
      teamComposition: "PM, iOS-разработчик, Android-разработчик, backend",
      decisionMaker: "CPO",
      hiringStages: 2,
      scoringCriteria: [
        { criterion: "Мобильный дизайн", weight: 30, type: "required" },
        { criterion: "Продуктовое мышление", weight: 25, type: "required" },
        { criterion: "B2C опыт", weight: 15, type: "required" },
        { criterion: "Геймификация / engagement", weight: 10, type: "nice_to_have" },
        { criterion: "A/B тестирование", weight: 10, type: "nice_to_have" },
        { criterion: "Motion design", weight: 10, type: "nice_to_have" },
      ],
    },
  });

  console.log("Создано 2 вакансии");
  console.log("Seed завершён!");
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
